apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "goserver"
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "joaocsv/hello-go:v2"
          envFrom:
            - configMapRef:
                name: goserver-env

          #env:
          #  - name: "NAME"
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: NAME
          #  - name: "VERSION"
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: VERSION

          #env:
          #  - name: "NAME"
          #    value: "Sistema de Teste"
          #  - name: "VERSION"
          #    value: "1.200"
