apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "goserver"
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "joaocsv/hello-go:v3.2"
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/version"
              name: versions
              readOnly: true

      volumes:
        - name: versions
          configMap:
            name: configmap-file
            items:
              - key: versions
                path: "versions.txt"

          #env:
          #  - name: "NAME"
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: NAME
          #  - name: "VERSION"
          #    valueFrom:
          #      configMapKeyRef:
          #        name: goserver-env
          #        key: VERSION

          #env:
          #  - name: "NAME"
          #    value: "Sistema de Teste"
          #  - name: "VERSION"
          #    value: "1.200"
