apiVersion: v1
kind: Service
metadata:
  name: "goserver-service"
spec:
  selector:
    app: "goserver"
  type: NodePort
  ports:
    - name: goserver-service
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007 #30000 - 32767
